// AUTO-GENERATED from MSI_Egen_Campaign_Map.xlsx + manual additions, then
// hand-curated. `assetType` is the normalized marketing-asset bucket (archive
// groups by it, then by `industry`). `status` drives the badge + link.
// `interview: true` marks customer stories that involved an interview.
export const workArchive = [
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title:
      'Trident X, Infinite S, Optix MPG341CQR, Prestige PS341WU + Innovation Award honorees',
    year: '2019',
    type: 'Blog',
    status: 'archived',
    url: 'https://web.archive.org/web/20220516052905/https://www.msi.com/blog/msi-ces-2019-recap-awards-and-honors',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title:
      'Optix MEG381CQR, MAG161, MEG Aegis Ti5, Prestige P100 (Innovation Awards)',
    year: '2020',
    type: 'Blog',
    status: 'archived',
    url: 'https://web.archive.org/web/20230602155203/https://www.msi.com/blog/CES2020-MSI-Hero-Products',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MAG Forge 100 / Creator 400 PC cases',
    year: '2020',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MAG Core Liquid AIO coolers',
    year: '2020',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'Creator PS321, MEG381CQR, MAG342CQR 1000R, MAG161 monitors',
    year: '2020',
    type: 'Blog',
    status: 'archived',
    url: 'https://web.archive.org/web/20250317220354/https://www.msi.com/blog/CES2020-monitor-lineup',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'CES',
    title: 'MAG Forge 100R/100M/101M cases',
    year: '2020',
    type: 'PR',
    status: 'press',
    url: 'https://www.msi.com/news/detail/SteadfastandBattleReadytheMAGForge100SeriesIsHere12840',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title:
      'Creator P50 desktop, Summit MS321UP (content creation/productivity)',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-ces-2021-content-creation-productivity-pc',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MEG Z490 GODLIKE + CES 2021 Innovation honorees',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MEG Z590 GODLIKE + Z590 lineup',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'Oculux NXG253R, MPG ARTYMIS 343CQR monitors',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-ces-2021-monitors',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MEG Z690 GODLIKE + PC-hardware honorees',
    year: '2022',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MEG Aegis Ti5 12th + 12th-gen desktops',
    year: '2022',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/CES-2022-Round-up-MSI-12th-Gen-Gaming-and-Business-Desktops',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'B660 motherboards (Alder Lake)',
    year: '2022',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'B760 motherboards',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/ces-2023-unveil-msi-b760-motherboards-for-13th-generation-intel-raptor',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MEG Z790 GODLIKE + CES 2023 honorees',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-ces-2023-round-up-meet-our-pc-hardware-innovation-award-honorees',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'PROJECT ZERO motherboards & cases, magnetic fans',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/ces-2024-round-up-cable-free-motherboards-cases-and-the-latest-pc-components',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'QD-OLED monitors, 14th-gen AI desktops, Claw',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/ces-2024-round-up-qd-oled-gaming-monitors-14th-gen-ai-gaming-desktop-and-more',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MPG Z890I EDGE TI + 5 Innovation Award winners',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/ces-2025-innovation-award-roundup-a-testament-to-continuing-excellence',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MPG 272URX QD-OLED + monitor lineup',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/ces-2025-monitor-round-up-oleds-mini-leds-600-hz-refresh-rates-and-more',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'X870E/B850 motherboards (AMD)',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/next-level-amd-ryzen-b850-and-x870e-motherboards-at-ces-2025',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'Z890/B860 motherboards (Intel)',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/the-z890-and-b860-motherboards-for-intel-core-ultra-at-ces-2025-where-performance-meets-ease',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'MEG MAESTRO 900L PZ case, PSUs, components',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/ces-2025-discover-our-new-pc-components-with-gaming-psus-liquid-coolers-and-cases',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'RTX 50 VANGUARD GPUs (GNP)',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/rtx-5090-5080-5070-vanguard',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'RTX 50 SUPRIM LIQUID GPUs (GNP)',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/RTX-5090-SUPRIM-LIQUID-GPU-Thermal',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'RTX 50 buying/upgrade guide (GNP)',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/how-to-upgrade-to-rtx-50-series-graphics-cards',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'PSUs w/ GPU Safeguard, coolers, Maestro 900R',
    year: '2026',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-ces-2026-pc-parts-roundup-worlds-first-gpu-safeguard-power-supplies-cooling-and-meg-maestro-900r',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'CES',
    title: 'PRO Series / PRO MAX professional hardware',
    year: '2026',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/meet-msi-pro-max-lineup-ces-2026-desktops-monitors-pc-parts-for-modern-minimalist-workspaces',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: 'MEG/MPG/MAG segments + new PRESTIGE lineup',
    year: '2019',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex (Tech Meets Aesthetics)',
    title: 'Summit MS321UP monitor, Creator P50',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-product-launch-2021-monitor-desktop-for-work',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex (Tech Meets Aesthetics)',
    title: 'MAG Infinite S3 gaming desktop',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-product-launch-2021-mag-infinite-s3',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex (Tech Meets Aesthetics)',
    title: 'MPG Quietude 100S case',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex (Tech Meets Aesthetics)',
    title: 'Optix MPG341QR + gaming monitors',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-product-launch-2021-next-gen-gaming-monitors',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: 'Modern MD271UL + Business & Productivity lineup',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/computex-2023-round-up-business-productivity-pcs-and-monitors',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: 'MEG Z790 GODLIKE + gaming lineup',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/computex-2023-round-up-Latest-msi-products-for-gamers',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: 'MEG/MPG/MAG brands + PC components',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/computex-2024-round-up-latest-motherboards-and-pc-components',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: 'AI gaming desktops + monitors (Best Choice honorees)',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/computex-2024-round-up-ai-gaming-desktop-monitor-best-choice-award-honorees',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: '800-series AMD motherboards (MEG X870E ACE)',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/new-gaming-motherboards-roundup-at-computex-2025',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: 'MEG CORELIQUID E13 360 + AIO coolers, PSUs, cases',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/computex-2025-pc-components-roundup-innovative-liquid-coolers-reliable-power-supplies-and-sleek-pc-cases',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: 'MPG 271QR QD-OLED X50 monitor + AI desktops',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/computex-2025-highlights-intelligent-monitors-and-desktops-with-ai-features-for-gaming-and-productivity',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: 'MEG X870E UNIFY-X MAX + PC components',
    year: '2026',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-computex-2026-pc-component-lineup-best-new-motherboards-coolers-casas-and-psus',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Computex',
    title: 'MPG OLED 322URDX36, MEG X monitors + desktops',
    year: '2026',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-computex-2026-ai-gaming-desktops-qd-oled-monitors-and-pro-max-series',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday',
    title: 'White & RGB themed PC parts',
    year: '2018',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/the-best-holiday-pc-gifts-for-2018-rgb-theme-vs-white-theme',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday / Christmas',
    title: 'Influencer gift picks (Optix MPG27CQ, MEG Z390 ACE)',
    year: '2018',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/best-tech-gift-ideas-under-1225',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday / Christmas',
    title: 'High-end holiday gaming PC build',
    year: '2020',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/deck-the-halls-with-boughs-of-holly-upgrade-your-gaming-pc-in-time-for-the-holiday-season',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday / Christmas',
    title: 'Christmas gift ideas (MEG B550 Unify)',
    year: '2020',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday',
    title: 'B&P monitors/AIOs/desktops + rewards',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday / Christmas',
    title: 'Z690 motherboards (Alder Lake)',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday',
    title: 'Console gaming monitors (PS5/Xbox, Console Mode)',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-holiday-gift-guide-2021-bes-console-gaming-monitors-for-ps5-ps4-and-xbox',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday',
    title: 'PRO business desktops (PRO DP130)',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday',
    title: 'Gaming desktops + monitors (MPG Trident)',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Black Friday',
    title: 'Tiered setups (MAG274R, MAG Codex 5)',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday',
    title: 'Pre-built PCs for home/office (~year est.)',
    year: '2022',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday / Christmas',
    title: 'Gaming gifts under $500 (WiFi, peripherals)',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/2023-best-holiday-gift-guide-for-gamer-under-500',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Holiday / Christmas',
    title: 'Premium gifts under $2000 (RTX 40 GPUs)',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/2023-best-holiday-gift-guide-for-gamer-under-2000',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: '1000R Monitor (ARTYMIS)',
    title: '1000R vs 1500R vs 1800R',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/1000r-vs-1500r-vs-1800r-curved-monitor',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: '1000R Monitor (ARTYMIS)',
    title: 'Why upgrade to 1000R (10 Reasons)',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/why-you-should-upgrade-to-1000R-curved',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: '1000R Monitor (ARTYMIS)',
    title: '1000R Netflix / Movies',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: '1000R Monitor (ARTYMIS)',
    title: 'Campaign landing',
    year: '2021',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/MSI-Artymis-series',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'EVA x MSI (Evangelion)',
    title: 'Partnership GTM press release',
    year: '2022',
    type: 'PR',
    status: 'press',
    url: 'https://www.msi.com/news/detail/Be-brave-to-get-in-that-machine--MSI-teams-up-with-EVANGELION-e--PROJECT-to-build-an-ultimate-gaming-PC-that-will-make-true-Evangelion-fans-drool-139863',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'EVA x MSI (Evangelion)',
    title: 'Campaign landing',
    year: '2022',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/evangelion-gaming-pc-components',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'MyMSI App',
    title: 'App landing page',
    year: '2022',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/app-mymsi',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'MyMSI App',
    title: 'Launch PR',
    year: '2022',
    type: 'PR',
    status: 'press',
    url: 'https://www.msi.com/news/detail/MSI-Launches-MyMSI-App-and-Now-Available-on-iOS-and-Android-139970',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'MyMSI App',
    title: 'App Store description',
    year: '2022',
    type: 'Store copy',
    status: 'internal',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'MSI Reward Program',
    title: 'Reward Program launch PR',
    year: '2023',
    type: 'PR',
    status: 'press',
    url: 'https://www.msi.com/news/detail/MSI-Reward-Program-Launches---Seeking-MSI-Allies-143578',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'MSI Reward Program',
    title: 'Meet the New Reward Program',
    year: '2023',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/meet-the-new-msi-reward-program',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'MSI Reward Program',
    title: 'Revamped Rewards PR',
    year: '2021',
    type: 'PR',
    status: 'press',
    url: 'https://www.msi.com/news/detail/MSIIntroducesaRevampedRewardsProgramwithMoreRewardsforTheirLoyalUsers122117',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'MSI Reward Program',
    title: 'Rewards blog / 2.0 site text / social posts',
    year: '2022',
    type: 'Blog/Web',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-rewards',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'WFH Campaign',
    title: '2021 WFH blog series (1-4)',
    year: '2021',
    type: 'Blog x4',
    status: 'internal',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'WFH Campaign',
    title: 'Remote work workspace setup',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://us.msi.com/blog/remote-work-workspace-setup',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'WFH Campaign',
    title: '8 tips to boost productivity',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/8-useful-tips-to-boost-your-productivity',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'DDR5',
    title: 'DDR5 benchmarks w/ Alder Lake',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/a-closer-look-at-ddr5-benchmarks-with-intels-Alder-lake-cpus',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'DDR5',
    title: 'DDR5 blog (general)',
    year: '2022',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'MSI Care / Warranty',
    title: 'MSI Care landing',
    year: '2021',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/msi-care',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'MSI Care / Warranty',
    title: 'Care Plus / Essential Service Pack',
    year: '2022',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/msi-care',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'MSI Care / Warranty',
    title: 'Warranty Extension PR',
    year: '2021',
    type: 'PR',
    status: 'none',
    url: '',
  },
  {
    industry: 'Cybersecurity',
    assetType: 'Landing pages & Web copy',
    campaign: 'Norton 360',
    title: 'Partnership landing / PR',
    year: '2022',
    type: 'Landing/PR',
    status: 'live',
    url: 'https://www.msi.com/Landing/norton-360-free-trial-redeem',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Metaverse',
    title: 'The Metaverse is almost here',
    year: '2021',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/the-metaverse-is-almost-here-are-you-ready',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Spark Your Productivity',
    title: 'Campaign landing / PR',
    year: '2022',
    type: 'Landing/PR',
    status: 'live',
    url: 'https://us.msi.com/Landing/spark-your-productivity',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: '35th Anniversary',
    title: 'Together, Create a Perfect Match',
    year: '2021',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/msi-35th-anniversary-perfect-match',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: '35th Anniversary',
    title: 'Anniversary PR',
    year: '2021',
    type: 'PR',
    status: 'press',
    url: 'https://www.msi.com/news/detail/LetscelebrateMSIs35thAnniversaryTogethercreateaperfectmatch122360',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'Stadium of Spoils (Z490)',
    title: 'Tournament PR / promo',
    year: '2020',
    type: 'PR/Promo',
    status: 'live',
    url: 'https://www.msi.com/Promotion/MSI-Stadium-of-Spoils',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: '3 Million Monitors Sold',
    title: 'Milestone landing / PR',
    year: '2021',
    type: 'Landing/PR',
    status: 'live',
    url: 'https://us.msi.com/Landing/3-million-gaming-monitors-sold',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'EYE Love Cinema',
    title: 'Promo + blog',
    year: '2022',
    type: 'Promo/Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/eye-love-cinema',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'Expand Your Horizon',
    title: 'Extended monitor promo',
    year: '2020',
    type: 'Promo',
    status: 'live',
    url: 'https://www.msi.com/Promotion/extended-monitor',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Monitor Ambassador',
    title: 'Ambassador / Streamer of Tomorrow landing',
    year: '2021',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/MSI-monitor-ambassador',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'Voicemod',
    title: 'Partnership PR / blog / landing',
    year: '2023',
    type: 'PR/Blog/Landing',
    status: 'live',
    url: 'https://www.msi.com/blog/voicemod-and-msi-join-forces-for-the-best-streaming-experience',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'DigiME (AI VTuber)',
    title: 'Launch PR / landing / blog',
    year: '2025',
    type: 'PR/Landing/Blog',
    status: 'live',
    url: 'https://www.msi.com/Landing/digime-ai-virtual-avatar',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Alessi collab',
    title: 'Collaboration blog',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'PC Config Tool',
    title: 'Config tool landing',
    year: '2022',
    type: 'Landing',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Gaming Chair (MAG CH)',
    title: 'Gaming chair blog / campaign',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Monitor education',
    title: 'Ultimate 2020 Gaming Monitor Buying Guide',
    year: '2020',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/2020-gaming-monitor-buying-guide',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Monitor education',
    title: 'Curved vs Flat monitors',
    year: '2019',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/curved-vs-flat-monitors-things-you-should-know-before-buying-gaming-monitors',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Monitor education',
    title: 'Ultrawide vs Dual monitor setup',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/factors-to-consider-when-picking-between-an-ultrawide-and-dual-monitor-setup',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Monitor education',
    title: 'Connect laptop to multiple monitors',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/connect-your-laptop-to-multiple-gaming-monitors',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Monitor education',
    title: 'Build best multi-monitor setups',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/build-the-best-multi-monitor-setups-for-gaming-and-streaming',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Monitor education',
    title: 'Multiple-monitor landing',
    year: '2023',
    type: 'Landing',
    status: 'live',
    url: 'https://us.msi.com/Landing/gaming-with-dual-triple-multi-monitors-setups',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Monitor education',
    title: 'Monitor Buying Guide / Resolution Refresh / Landing proofing',
    year: '2020',
    type: 'Blog/Landing',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Monitor education',
    title: 'Mac / Console / Display-problems landing blogs (x3)',
    year: '2023',
    type: 'Blog x3',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Monitor education',
    title: 'Console Monitor Marketing',
    year: '2021',
    type: 'Landing',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Monitor education',
    title:
      'Product blogs: MAG271CQR, MAG321CURV, MPG341CQ(R), Prestige PS341WU, Prestige Lineup, Infinite S',
    year: '2019',
    type: 'Product blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Motherboard / chipset / BIOS',
    title: 'B450 vs B550 vs X570',
    year: '2020',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-b450-b550-x570-comparison',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Motherboard / chipset / BIOS',
    title: 'X470 vs X570',
    year: '2020',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/amd-x470-vs-x570-chipset-motherboard-comparison',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Motherboard / chipset / BIOS',
    title: 'How to choose a motherboard',
    year: '2020',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/how-to-choose-a-motherboard',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Motherboard / chipset / BIOS',
    title: 'Click BIOS X',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-click-bios-x-revealed-simplified-overclocking-new-looks-and-unmatched-control',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Motherboard / chipset / BIOS',
    title:
      'B350 vs B450, Z370 vs Z390, Z390 lineup, Z490 OC, MAX boards, UEFI/BIOS, Bulletproof, X3D/X870E, Arrow Lake',
    year: '2019',
    type: 'Blog',
    status: 'internal',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'GPU / graphics',
    title: 'RTX 40 PSU / ATX 3.0 guide',
    year: '2022',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/atx-30-the-best-power-supply-units-for-your-geforce-rtx-40-series',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'GPU / graphics',
    title: 'MSI Afterburner OC/UV guide',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/msi-afterburner-overclocking-undervolting-guide',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'GPU / graphics',
    title:
      'RTX 30-series, SUPRIM Liquid, Trio, Why Liquid, Master Series, Blackwell scripts',
    year: '2024',
    type: 'Blog/Script',
    status: 'internal',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'AI on RTX / creator',
    title: 'Stable Diffusion XL best-value GPU',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/stable-diffusion-xl-best-value-rtx-graphics-card',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'AI on RTX / creator',
    title: 'Stable Diffusion + AnimateDiff benchmark',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/stable-diffusion-animatediff-benchmark-rtx-4070-ti-super',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'AI on RTX / creator',
    title: 'AI on RTX landing',
    year: '2024',
    type: 'Landing',
    status: 'live',
    url: 'https://us.msi.com/Landing/geforce-rtx-graphics-cards-ai-on-rtx',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'AI on RTX / creator',
    title: 'Black Myth Wukong settings',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/the-best-value-graphics-card-for-black-myth-wukong-rtx-4070-super',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'AI on RTX / creator',
    title: 'Monster Hunter Wilds settings',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/rtx-50-benchmarks-monster-hunter-wilds-best-setting-guide',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'AI on RTX / creator',
    title: 'Battlefield 6 + Afterburner',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/battlefield-6-beta-msi-afterburner-how-to-setup-guide',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'AI on RTX / creator',
    title:
      'Doom, Cinepacks, creator case studies (Liam Young/Gerde/Yokohara), Local AI landing',
    year: '2025',
    type: 'Blog/Case study',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Networking & storage',
    title: 'What is Wi-Fi 7',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/what-is-wifi-7',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Networking & storage',
    title: 'Wi-Fi 6E AXE5400 adapter',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/axe5400_wifi6e_usb_adapter',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Networking & storage',
    title: 'Get ready for Wi-Fi 6E',
    year: '2022',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/get-ready-for-wi-fi-6e',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Networking & storage',
    title: 'Roamii Wi-Fi 7 mesh',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/upgrade-to-an-affordable-wifi-7-mesh-introducing-the-msi-roamii-mesh-systems',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Networking & storage',
    title: 'Is a gaming router worth it (benefits)',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/benefit-of-gaming-router',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Networking & storage',
    title: 'What is MSI AI QoS',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/what-is-msi-ai-qos',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Networking & storage',
    title: 'AI QoS benefits',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/benefits-of-msi-ai-qos',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Networking & storage',
    title: 'High-capacity SSD benefits',
    year: '2023',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/benefits-of-high-capacity-ssd',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Networking & storage',
    title: 'PCIe 5.0 SSD, Wi-Fi 6 scripts',
    year: '2024',
    type: 'Blog/Script',
    status: 'internal',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'PC build / DIY / buying',
    title: 'Prebuilt vs Custom PC',
    year: '2025',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/how-to-choose-the-best-gaming-pc-custom-vs-prebuilt-and-core-specs-explained',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'PC build / DIY / buying',
    title: 'PC cleaning for thermals',
    year: '2022',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/a-guide-to-cleaning-your-system-for-better-performance-and-thermals',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'PC build / DIY / buying',
    title:
      'ATX/mATX/ITX builds, Streaming PC, Thermals, RGB/USB refresh, Q1 Intel/AMD buying & build guides, Dream PC, Deals guide',
    year: '2022',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'VTuber / streaming',
    title: 'What you need to become a VTuber',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/what-do-you-need-to-become-a-vtuber',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'VTuber / streaming',
    title: 'Bare-minimum VTuber setup',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/bare-minimum-streaming-setup-for-vtubers',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'VTuber / streaming',
    title: 'Recommended / best VTuber setup',
    year: '2024',
    type: 'Blog',
    status: 'live',
    url: 'https://www.msi.com/blog/create-your-best-vtuber-streaming-setup',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'VTuber / streaming',
    title: 'Streamer Hub landing',
    year: '2024',
    type: 'Landing',
    status: 'live',
    url: 'https://us.msi.com/Landing/streamer-hub-for-best-streaming-pc',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Cases & cooling',
    title: 'MPG Sekira 500, MSI Case Article, Quietude',
    year: '2019',
    type: 'Blog/NDA',
    status: 'internal',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Case studies & Customer stories',
    campaign: 'Case Studies',
    title:
      'Sifter - personalized nutrition platform (DevOps / serverless modernization)',
    year: '2021',
    type: 'Case study',
    status: 'archived',
    url: 'http://web.archive.org/web/20230925055128/https://egen.solutions/our-work/sifter/',
  },
  {
    industry: 'Cloud',
    assetType: 'Case studies & Customer stories',
    campaign: 'Case Studies',
    title:
      "Caterpillar / Progress Rail - Uptime predictive maintenance (= progress-rail-case-study + Case Study 1 'Cloud Costs' + Case Study 3)",
    year: '2020',
    type: 'Case study',
    status: 'live',
    url: 'https://egen.ai/customer-stories/caterpillar-building-predictive-maintenance-models/',
  },
  {
    industry: 'Cloud',
    assetType: 'Case studies & Customer stories',
    campaign: 'Case Studies',
    title:
      'Integra Connect - real-time data platform, precision medicine (in Case Study data / Collation)',
    year: '2021',
    type: 'Case study',
    status: 'archived',
    url: 'http://web.archive.org/web/20230601113819/https://egen.solutions/our-work/integra-connect/',
  },
  {
    industry: 'Cloud',
    assetType: 'Case studies & Customer stories',
    campaign: 'Case Studies',
    title:
      "Tempus - genomic/clinical data ingestion pipeline (anonymized 'ACME CORP' draft)",
    year: '2023',
    type: 'Case study',
    status: 'none',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Other',
    campaign: 'Case Studies',
    title: 'Case Study Collation / Case Study data.txt (research notes)',
    year: '2020',
    type: 'Research notes',
    status: 'internal',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: 'Cloud Costs blog (Blog_1, v1.0 / v1.3.1)',
    year: '2021',
    type: 'Blog',
    status: 'archived',
    url: 'http://web.archive.org/web/20230925065210/https://egen.solutions/articles/how-to-reduce-aws-costs-strategies-and-best-practices/',
  },
  {
    industry: 'Cloud',
    assetType: 'Case studies & Customer stories',
    campaign: 'Blogs & Whitepapers',
    title: '10 Ways to Reduce Cloud Costs (whitepaper PDF)',
    year: '2020',
    type: 'Whitepaper',
    status: 'archived',
    url: 'http://web.archive.org/web/20240623080931/https://insights.egen.solutions/hubfs/white-papers/10%20Ways%20to%20Reduce%20Cloud%20Costs.pdf',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: 'Spot Instances on EC2 / Kubernetes (Blog_2 + Overflow)',
    year: '2020',
    type: 'Blog',
    status: 'archived',
    url: 'http://web.archive.org/web/20230601122438/https://egen.solutions/articles/running-kubernetes-workload-on-amazon-ec2-spot-instances/',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: "AWS re:Invent in Review - Part 1 (Week 1 + 'AWS re;Invent')",
    year: '2020',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: 'AWS re:Invent in Review - Part 2 (Week 2)',
    year: '2020',
    type: 'Blog',
    status: 'archived',
    url: 'http://web.archive.org/web/20210412213729/https://www.egen.solutions/blogs/aws-reinvent-review2',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: 'AWS re:Invent in Review - Part 3 (Week 3)',
    year: '2021',
    type: 'Blog',
    status: 'archived',
    url: 'http://web.archive.org/web/20230601113550/https://egen.solutions/articles/aws-reinvent-2020-part-3/',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: 'A Deep-Dive into Downtime (Downtime_1 + Downtime_2)',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: 'Checklist to Eliminate Software Downtime (DevOps_Checklist)',
    year: '2021',
    type: 'Blog / checklist',
    status: 'archived',
    url: 'http://web.archive.org/web/20230601120010/https://egen.solutions/articles/software-downtime-checklist/',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: 'DevOps overview (DevOps v1.1 / Short / Rough deck)',
    year: '2020',
    type: 'Blog / deck',
    status: 'archived',
    url: 'http://web.archive.org/web/20210225141024/https://egen.solutions/blogs/cloud-native-applications',
  },
  {
    industry: 'Cloud',
    assetType: 'Other',
    campaign: 'Blogs & Whitepapers',
    title: 'Webinar - Downtime / reliability',
    year: '2021',
    type: 'Webinar',
    status: 'internal',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: 'Demand Forecasting & Amazon Forecast Index',
    year: '2021',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Blogs & Articles',
    campaign: 'Blogs & Whitepapers',
    title: 'kdx - Kubernetes deployment accelerator (kdx Blog_1)',
    year: '2020',
    type: 'Product blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Landing pages & Web copy',
    campaign: 'Rebrand & Sales',
    title: 'Modernize page (Modernization Master / Layout Filled)',
    year: '2021',
    type: 'Web page',
    status: 'archived',
    url: 'http://web.archive.org/web/20230925063924/https://egen.solutions/what-we-do/',
  },
  {
    industry: 'Cloud',
    assetType: 'Landing pages & Web copy',
    campaign: 'Rebrand & Sales',
    title: 'Scale page',
    year: '2021',
    type: 'Web page',
    status: 'archived',
    url: 'http://web.archive.org/web/20230925065443/https://egen.solutions/what-we-do/scale/',
  },
  {
    industry: 'Cloud',
    assetType: 'Landing pages & Web copy',
    campaign: 'Rebrand & Sales',
    title: 'Launch page (Peapod same-day grocery)',
    year: '2021',
    type: 'Web page',
    status: 'archived',
    url: 'http://web.archive.org/web/20230925060906/https://egen.solutions/what-we-do/launch/',
  },
  {
    industry: 'Cloud',
    assetType: 'Landing pages & Web copy',
    campaign: 'Rebrand & Sales',
    title: 'egen-modernize-scale-launch (combined draft)',
    year: '2021',
    type: 'Web copy',
    status: 'none',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Other',
    campaign: 'Rebrand & Sales',
    title: 'Webflow site capture (screenshot)',
    year: '2021',
    type: 'Asset',
    status: 'internal',
    url: '',
  },
  {
    industry: 'Cloud',
    assetType: 'Other',
    campaign: 'Rebrand & Sales',
    title: 'Egen pitch deck',
    year: '2020',
    type: 'Sales deck',
    status: 'internal',
    url: '',
  },
  {
    industry: 'Cybersecurity',
    assetType: 'Blogs & Articles',
    campaign: 'RedLegg',
    title: 'Vulnerability Management - comprehensive guide',
    year: '2019',
    type: 'Blog',
    status: 'live',
    url: 'https://www.redlegg.com/solutions/advisory-services/vulnerability-management-pretty-much-everything-you-need-to-know',
  },
  {
    industry: 'Cybersecurity',
    assetType: 'Blogs & Articles',
    campaign: 'RedLegg',
    title:
      "Ransomware & DHS guidelines (DHS Guidelines = 'New Microsoft Word Document', same piece)",
    year: '2020',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'Cybersecurity',
    assetType: 'Blogs & Articles',
    campaign: 'RedLegg',
    title: 'Hybrid Cloud (top-of-funnel)',
    year: '2019',
    type: 'Blog',
    status: 'none',
    url: '',
  },
  {
    industry: 'Cybersecurity',
    assetType: 'Blogs & Articles',
    campaign: 'RedLegg',
    title: 'Diversifying Threat Intel Feeds',
    year: '2019',
    type: 'Blog',
    status: 'live',
    url: 'https://www.redlegg.com/managed-security-services/threat-intelligence/operationalize-data-guide',
  },
  {
    industry: 'Cybersecurity',
    assetType: 'Blogs & Articles',
    campaign: 'RedLegg',
    title: 'The hidden cost of cyber threats (Yahoo / Deloitte)',
    year: '2019',
    type: 'Blog',
    status: 'live',
    url: 'https://www.redlegg.com/blog/major-data-breaches',
  },
  {
    industry: 'Cybersecurity',
    assetType: 'Other',
    campaign: 'RedLegg',
    title: "RedLegg homepage (the 'Redlegg - Link' doc)",
    year: '2020',
    type: 'Reference',
    status: 'archived',
    url: 'https://web.archive.org/web/20201101013036/https://www.redlegg.com/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'RTX 4080 SUPER review (RTX 4080 Super_Review)',
    year: '2024',
    type: 'GPU review',
    status: 'live',
    url: 'https://www.cgdirector.com/nvidia-rtx-4080-super-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'RTX 4070 Ti SUPER review',
    year: '2024',
    type: 'GPU review',
    status: 'live',
    url: 'https://www.cgdirector.com/nvidia-rtx-4070-ti-super-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'RTX 4070 SUPER review',
    year: '2024',
    type: 'GPU review',
    status: 'live',
    url: 'https://www.cgdirector.com/nvidia-rtx-4070-super-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'Reviews',
    title: 'RTX 40 SUPER series announcement (RTX 4070 Super Launch)',
    year: '2024',
    type: 'News',
    status: 'live',
    url: 'https://www.cgdirector.com/nvidia-geforce-rtx-40-super-series-announcement/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'RTX 4080 16GB review (RTX 4080 - v0.1)',
    year: '2022',
    type: 'GPU review',
    status: 'live',
    url: 'https://www.cgdirector.com/rtx-4080-review-content-creation/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Reviews',
    title: 'Is RTX 4090/4080 worth it for creators (Nvidia RTX 4000)',
    year: '2022',
    type: 'Feature',
    status: 'live',
    url: 'https://www.cgdirector.com/nvidia-rtx-4000-worth-it/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'Radeon Pro W7900 & W7800 review',
    year: '2023',
    type: 'GPU review',
    status: 'live',
    url: 'https://www.cgdirector.com/amd-radeon-pro-w7900-w7800-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'Radeon Pro W6400 review',
    year: '2022',
    type: 'GPU review',
    status: 'live',
    url: 'https://www.cgdirector.com/amd-radeon-pro-w6400-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'Radeon Pro W5500 hands-on (Hands-on Radeon Pro W5500)',
    year: '2020',
    type: 'GPU review',
    status: 'live',
    url: 'https://www.cgdirector.com/amd-radeon-pro-w5500-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'ASUS ProArt Studiobook 16 review',
    year: '2022',
    type: 'Laptop review',
    status: 'live',
    url: 'https://www.cgdirector.com/asus-proart-studiobook-16-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'ASUS Pro Duo hands-on (ASUS Pro Duo_Second Draft)',
    year: '2020',
    type: 'Laptop review',
    status: 'live',
    url: 'https://www.cgdirector.com/asus-pro-duo-hands-on-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'AMD Ryzen 5000 review (Zen 3 Release)',
    year: '2020',
    type: 'CPU review',
    status: 'live',
    url: 'https://www.cgdirector.com/amd-ryzen-5000-series-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'AMD Threadripper 3990X review (3990X / Final Draft / Draft v7)',
    year: '2020',
    type: 'CPU review',
    status: 'live',
    url: 'https://www.cgdirector.com/amd-threadripper-3990x-review/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'Reviews',
    title: 'Threadripper 3000 launch (Threadripper 3000 Launch Article)',
    year: '2019',
    type: 'News',
    status: 'live',
    url: 'https://www.cgdirector.com/threadripper-3000-platform-details-release-date/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'Nvidia RTX 3000 (RTX 3000 - v1.1)',
    year: '2020',
    type: 'Review/News',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Reviews',
    campaign: 'Reviews',
    title: 'Intel 10th Gen CPUs (Intel 10th Generation v1/v2)',
    year: '2020',
    type: 'Review/News',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'Reviews',
    title: 'AMD @ Computex 2024 (AMD_Computex_2024)',
    year: '2024',
    type: 'News',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'What is CPU IPC (IPC Explained)',
    year: '2022',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/what-is-cpu-ipc/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'P-Cores vs E-Cores (Alder Lake P & E Cores)',
    year: '2022',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/p-cores-vs-e-cores/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'Guide to RAM (Memory) Latency',
    year: '2022',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/ram-memory-latency/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'MT/s vs MHz',
    year: '2022',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/mts-vs-mhz/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'DDR4 vs DDR5 (DDR5 vs. DDR4)',
    year: '2023',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/ddr4-vs-ddr5/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'DDR5 & Ryzen 7000 Buyer Beware (DDR5_Split)',
    year: '2023',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/ddr5-ram-ryzen-beware/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'LGA vs PGA sockets (TechBits - CPU Sockets)',
    year: '2022',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/lga-vs-pga/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'How to fix bent CPU pins (LGA-PGA Bent Pins)',
    year: '2022',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/how-to-fix-bent-cpu-pins/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'Intel Core vs AMD Ryzen (Intel vs AMD / Intel vs Ryzen)',
    year: '2024',
    type: 'Comparison',
    status: 'live',
    url: 'https://www.cgdirector.com/intel-core-vs-amd-ryzen/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'Nvidia vs AMD GPUs (Nvidia vs. AMD GPUs)',
    year: '2024',
    type: 'Comparison',
    status: 'live',
    url: 'https://www.cgdirector.com/nvidia-geforce-vs-amd-radeon-gpus/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'Guide to Undervolting your GPU (Undervolting)',
    year: '2024',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/guide-to-undervolting-your-gpu/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Explainers',
    title: 'TiB vs TB (TiB and TB)',
    year: '2022',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/tib-vs-tb/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best AM5 motherboards (AM5 Motherboards)',
    year: '2023',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-am5-motherboards/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best Z690 & Z790 motherboards (Z690 / Z790 Raptor Lake)',
    year: '2023',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-z690-z790-motherboards/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best Z590 motherboards',
    year: '2021',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-z590-motherboards-for-intel-11900k-11700k-11600k/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best Z490 motherboards',
    year: '2020',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-z490-motherboards-intel-10th-gen-cpus/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best B550 motherboards',
    year: '2020',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-b550-motherboards/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best B450 motherboards',
    year: '2020',
    type: 'Guide',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best B560 motherboards',
    year: '2021',
    type: 'Guide',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best motherboards Intel 9th Gen 9900K (Intel Motherboards)',
    year: '2019',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-motherboards-intel-9th-gen-9900k/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best motherboards for Ryzen (Best Motherboards for Ryzen 3000)',
    year: '2019',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-motherboard-for-amd-ryzen-5000/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best gaming motherboards (Best Motherboards for Gaming)',
    year: '2022',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-motherboards-for-gaming/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best motherboard brands',
    year: '2022',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-motherboard-brands/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Motherboard buying guide (Motherboards_Pillar / Motherboards)',
    year: '2023',
    type: 'Pillar guide',
    status: 'live',
    url: 'https://www.cgdirector.com/motherboard-buying-guide-for-workstations/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Motherboard guides',
    title: 'Best Threadripper motherboards (Threadripper Motherboards)',
    year: '2022',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-motherboards-amd-threadripper-cpus-3970x-3960x/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'PSU / cooling',
    title: 'How to choose a PSU (PSU Pillar / Skeleton / Power Supply Units)',
    year: '2023',
    type: 'Pillar guide',
    status: 'live',
    url: 'https://www.cgdirector.com/power-supply-guide/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'PSU / cooling',
    title: 'PWM vs DC vs Auto fans (PWM v DC)',
    year: '2022',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/pwm-dc-system-fans/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Storage / PCIe',
    title: 'High Capacity SSDs (SSD size guide)',
    year: '2022',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/ssd-size/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Storage / PCIe',
    title: 'Storage pillar (Best NVMe SSDs)',
    year: '2022',
    type: 'Pillar guide',
    status: 'live',
    url: 'https://www.cgdirector.com/best-nvme-ssds/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Storage / PCIe',
    title: 'x8 vs x16 explanation (PCIe x16)',
    year: '2022',
    type: 'Explainer',
    status: 'live',
    url: 'https://www.cgdirector.com/what-does-pcie-x16-mean/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Laptops / builds',
    title: 'Laptop vs Desktop workstations (Laptop vs Desktop / Pros & Cons)',
    year: '2023',
    type: 'Comparison',
    status: 'live',
    url: 'https://www.cgdirector.com/laptop-vs-desktop-workstations/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Laptops / builds',
    title: 'Are MacBooks good for video editing (Mac PC)',
    year: '2020',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/are-macbooks-good-for-video-editing/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Laptops / builds',
    title: 'How to build a PC (PC Building Guide)',
    year: '2023',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/how-to-build-a-pc/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Laptops / builds',
    title: 'XMP memory profile guide (XMP Profiles)',
    year: '2021',
    type: 'Guide',
    status: 'live',
    url: 'https://www.cgdirector.com/xmp-memory-profile-guide/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Guides & Explainers',
    campaign: 'Laptops / builds',
    title: 'Holiday Gifting Guide',
    year: '2021',
    type: 'Guide',
    status: 'none',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Site / internal',
    title: 'Media & Outreach page (Media Outreach / Media Page)',
    year: '2021',
    type: 'Site page',
    status: 'live',
    url: 'https://www.cgdirector.com/media-outreach/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Blogs & Articles',
    campaign: 'Site / internal',
    title:
      'PC Builder tool content (PC Builder Laptops / PC_Builder_Edited / PC Part Sources)',
    year: '2021',
    type: 'Tool content',
    status: 'internal',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Press & PR',
    campaign: 'Site / internal',
    title: 'Newsletters 1-26 + Cloud Newsletter (CGDirector_Newsletter_*)',
    year: '2021',
    type: 'Email newsletters',
    status: 'internal',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Other',
    campaign: 'Site / internal',
    title:
      'Outlines & notes (3900X outline, RAM outline, Categories, Profile, CPU Power, CPU-GPU Pairs)',
    year: '2020',
    type: 'Outlines/notes',
    status: 'internal',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Other',
    campaign: 'Site / internal',
    title: 'Threadripper 3990X press kit + BIOS photos + timesheet',
    year: '2020',
    type: 'Assets',
    status: 'internal',
    url: '',
  },
  {
    industry: 'Software / SaaS',
    assetType: 'Blogs & Articles',
    campaign: 'LicenseSpring',
    title: 'FastSpring integration / Get Started announcement',
    year: '2019',
    type: 'Blog / PR',
    status: 'press',
    url: 'https://licensespring.com/blog/news/licensespring-integrated-with-fastspring',
  },
  {
    industry: 'Software / SaaS',
    assetType: 'Blogs & Articles',
    campaign: 'LicenseSpring',
    title: 'New platform, license models & SDKs + FastSpring',
    year: '2020',
    type: 'Blog / PR',
    status: 'press',
    url: 'https://licensespring.com/blog/news/announcement-new-platform-new-license-models-new-sdk',
  },
  {
    industry: 'Software / SaaS',
    assetType: 'Other',
    campaign: 'LicenseSpring',
    title: 'Delphi SDK - r/Delphi post (founder Edmon); links to announcement',
    year: '2020',
    type: 'Reddit post',
    status: 'press',
    url: 'https://licensespring.com/blog/news/announcement-new-sdk-for-delphi',
  },
  {
    industry: 'Software / SaaS',
    assetType: 'Landing pages & Web copy',
    campaign: 'LicenseSpring',
    title: 'Pricing page copy',
    year: '2019',
    type: 'Web page',
    status: 'live',
    url: 'https://licensespring.com/pricing',
  },
  {
    industry: 'Software / SaaS',
    assetType: 'Landing pages & Web copy',
    campaign: 'LicenseSpring',
    title: 'Get Started page copy',
    year: '2019',
    type: 'Web page',
    status: 'live',
    url: 'https://licensespring.com/get-started',
  },
  {
    industry: 'Software / SaaS',
    assetType: 'Landing pages & Web copy',
    campaign: 'LicenseSpring',
    title: "Homepage / landing + About Us ('Website Changes')",
    year: '2019',
    type: 'Web page',
    status: 'live',
    url: 'https://licensespring.com/',
  },
  {
    industry: 'Software / SaaS',
    assetType: 'Other',
    campaign: 'LicenseSpring',
    title:
      'Competitor SEMrush analysis (Soraco, Reprise, Cryptolens, ssware, Nalpeiron, SoftwareKey, Keygen)',
    year: '2019',
    type: 'Research PDFs',
    status: 'internal',
    url: '',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Brand',
    title: 'MSI brand story',
    year: '2024',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/about/brandStory',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'MSI University',
    title: 'MSI University landing',
    year: '2024',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/msi-university',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Buying guides',
    title: 'Best gaming desktop PC',
    year: '2024',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/best-gaming-desktop-pc',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Buying guides',
    title: 'Best PC build powered by MSI (+ accompanying guides)',
    year: '2024',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/best-pc-build-powered-by-msi',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Buying guides',
    title: 'Best 34" ultrawide & 32" QD-OLED gaming monitor',
    year: '2024',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/best-34-ultrawide-and-32-inch-qd-oled-gaming-monitor',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Landing pages & Web copy',
    campaign: 'Buying guides',
    title: 'Best monitor buying guide',
    year: '2024',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/best-monitor/buying-guide',
  },
  {
    industry: 'Cloud',
    assetType: 'Landing pages & Web copy',
    campaign: 'Egen rebrand',
    title: 'egen.ai homepage & rebrand',
    year: '2023',
    type: 'Web copy',
    status: 'live',
    url: 'https://egen.ai/',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'PRO MAX',
    title: 'PRO MAX product-line landing',
    year: '2026',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/pro-max',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'Lightning 2026',
    title: 'Lightning 2026 graphics cards landing',
    year: '2026',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/Lightning-2026/graphics-cards',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'NVIDIA DGX Station',
    title: 'NVIDIA DGX Station landing',
    year: '2026',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/NVIDIA-DGX-STATION',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'MEG Godlike',
    title: 'One MEG Godlike Moment landing',
    year: '2024',
    type: 'Landing',
    status: 'live',
    url: 'https://www.msi.com/Landing/one-meg-godlike-moment',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'Master Series (Creator GPUs)',
    title: 'Creator Master Series GPUs (landing + video script)',
    year: '2024',
    type: 'Landing + video script',
    status: 'live',
    url: 'https://www.msi.com/Landing/graphics-cards-for-creator-the-master-series/graphics-cards',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Product Launch',
    campaign: 'Liquid-cooled AI infrastructure',
    title:
      'Liquid-cooled AI infrastructure at Computex 2026 (NVIDIA MGX / DGX Station / DC-MHS)',
    year: '2026',
    type: 'Blog feature',
    status: 'press',
    url: 'https://www.msi.com/news/detail/MSI-Showcases-Liquid-Cooled-AI-Infrastructure--NVIDIA-MGX--NVIDIA-DGX-Station-and-DC-MHS-Platforms-at-COMPUTEX-2026-148789',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'AI infrastructure',
    title: 'MGX servers accelerate US-based AI infrastructure',
    year: '2026',
    type: 'Case study',
    status: 'live',
    url: 'https://eps.msi.com/en/customerstories/mgx-servers-accelerate-us-based-ai-infrastructure',
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'James Gerde - creator customer story',
    year: '2023',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/James_Gerde',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Cinepacks Studio - creator customer story',
    year: '2023',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/Cinepacks_studio',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'ZOA Studio - creator customer story',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/creator-customer-stories-zoa-studio',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Hirokazu Yokohara - virtual human AI/CG artist',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/hirokazu-yokohara-virtual-human-ai-cg-artist',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Liam Young - creator customer story',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/creator-customer-stories-liamyoung',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Oyvind Engevik (Engwind) - creator customer story',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/creator-customer-stories-yvind-engevik-engwind',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Peter Eszenyi - VFX supervisor',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/vfx-supervisor-peter-eszenyi',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Shutter Authority - creator customer story',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/creator-customer-stories-shutter-authority',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Jordy Vandeput - creator customer story',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/jordy-vandeput',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Nik Hill - motion graphics designer',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/motion-graphics-designer-nik-hill',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Jean-Denis Haas - animator',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/animator-Jean-Denis-Haas',
    interview: true,
  },
  {
    industry: 'PC Hardware',
    assetType: 'Case studies & Customer stories',
    campaign: 'Creator stories',
    title: 'Dale Hayward - stop-motion animator',
    year: '2024',
    type: 'Customer story',
    status: 'live',
    url: 'https://www.msi.com/case-study/stop-motion-animator-dale-hayward',
    interview: true,
  },
];
